### ISSUE TITLE
ログインしようとするとエラー

### ISSUE THREAD

**Issue by watepu** [y-516/group_work#3]
<img width="997" alt="2018-12-15 12 55 47" src="https://user-images.githubusercontent.com/40508321/50038838-1e83d380-006a-11e9-937c-7d9cf149bc80.png">
上記一文を消すとログイン出来るようになるのですが、これはどのような機能なのでしょうか？

**Comment by DAdDY0055** [comment]
sessionにログインするユーザのIDを入れる処理でした。

以下の行が誤りで、

`　    session[:user_id] = user.IndexError`

以下が正しいため修正します。

`　    session[:user_id] = user.id`

**Comment by DAdDY0055** [comment]
VSが勝手に補完していたのを見逃してました。。

<img width="683" alt="2018-12-15 13 25 43" src="https://user-images.githubusercontent.com/38724804/50039001-d666b000-006d-11e9-91cb-823553b150b2.png">
